
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author INFINIX
 */
public class pretest extends javax.swing.JFrame {

    /**
     * Creates new form pretest
     */
    public pretest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMhs = new javax.swing.JLabel();
        tfMhs = new javax.swing.JTextField();
        lbNilai = new javax.swing.JLabel();
        tfNilai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        lbMhs.setText("Mahasiswa");
        getContentPane().add(lbMhs);

        tfMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMhsActionPerformed(evt);
            }
        });
        getContentPane().add(tfMhs);

        lbNilai.setText("Nilai");
        getContentPane().add(lbNilai);

        tfNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNilaiActionPerformed(evt);
            }
        });
        getContentPane().add(tfNilai);
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel2);

        btSimpan.setText("Simpan");
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btSimpan);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMhsActionPerformed

    private void tfNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNilaiActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
       String Mahasiswa = new mahasiswa ;
       String Nilai = new Nliai ;
       
       JOptionPane.showMessageDialog(rootPane, Nilai);
        
    }//GEN-LAST:event_btSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pretest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pretest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pretest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pretest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pretest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbMhs;
    private javax.swing.JLabel lbNilai;
    private javax.swing.JTextField tfMhs;
    private javax.swing.JTextField tfNilai;
    // End of variables declaration//GEN-END:variables
}
